---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: atamagaii-api-secrets
  namespace: default
spec:
  encryptedData:
    config.yml: AgCghcwTGSgqg0w6tkvyfJt16Pgedxqu+7pD05RPZat/1xUjdtjn03GnNNrvoepDr3YQ7LqDjWuHZXkiwUU4zk8hCkBXbDWyhVRlkxOhS9XTkCNywrrlPLScnANZNxCipYqQd3n5v14tQ1XgodS/xyCsEuDvNgX1rfVkzlB4omK21u4946ghnyx3FlZV7ELQD2Mauo1kCfgEvyn/PZGJaUpawoG/SVMZNmx+qQgVmNVw5qH0iu33n+UiwennJVrLLijkJV4apjL9u4lLzhGOAgvE+lrI7sUn7hxx8jfrh/IbPH1p/pgELuqc5Loila+eemK6Gi6MYG1AwhPcfXFcNnUFxMGu0lGmqZR3XBI7D8r2eNPZO9OHxNGKdRc/+zdqB5cW8edJbtnlFCmFbUL3WFpeUZ2qQ4tHDCzlJo+ItqhrbPsMeGLM3IFjEulgdmCKOs2XxcqhOde224wm86Z7UrgEzWsSTHvKOZqn6+poVHvREqt9mRLwW+3z5IxGOr5mhMJUDk+Ar0fJIfLzDja8ilBg0/v/DLohIoy6bSnYjrRjGmxhvpCWEd6PVh39ZVx8Edxe0c5sy2FBJyUqcdIiSrECNy7lb6G9dz1/k9xAtThGfuqlxMn6gfeoII/3QBzYE/rvi2dnFP4aX+IDWhxWBGYCBolmchb8Mz9HHgB9e+kONtBgQuhqXNnW+/r51QcvWDeSquDftOHPvQR5a/46O57prxYc9RUn591c/4/r9t48adcvIYYXA0hljI01tA7Q31kA9/WSkxfuSbw81bgT1Y9cysO17HbLS1PXs1X5mi9hbtGlHKmyFwEjUBSwQjyOhvCC5lb7vY+OiTxn0VVEc3bRinbZ4vNy4+P/l7Qzb3fPxwYIHvGInQ57sdp/Vjxb+pXh9UMBZvG4rP3POKwlVNhWUOeWHir/xRA//E5QXuFtUgsf8oLbywNEgPbKbkK6Lln1fTVwNWaPC+n32Ja92Gg8c1UESvzAbJYcOUr8ZE40KQbGcl23f/vQL+hffVsl54HMPV8H9qjN4DLnXj3N3nNHezSVQ9KWswc3HZytYBEjnv97amlHw2D5oh/Ha4Y9JCQuMgPPuu9qa+I2vaB5FZDe4V74Da7RiKumoMKQp+hO3ZgEIuxBip1mKitR4CnP3TogfYcP+DvJVLNRKt+MCOb3hW4Vkz5Be2popt4zOmgYfbjV
  template:
    metadata:
      creationTimestamp: null
      name: atamagaii-api-secrets
      namespace: default
